sudo: required
env:
  global:
    - VERSION=$(cat ./version)
services:
  - docker

before_install:
  - docker build -t frontend_test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run frontend_test npm run test -- --coverage

after_success:
  - docker build -t jculvey/fib-frontend:$VERSION ./frontend
  - docker build -t jculvey/fib-api:$VERSION ./api
  - docker build -t jculvey/fib-worker:$VERSION ./worker
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jculvey/fib-frontend:$VERSION
  - docker push jculvey/fib-api:$VERSION
  - docker push jculvey/fib-worker:$VERSION
