apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: jculvey/fib-frontend:689af88f99d39396b7e47cf5ff915878f4a0dc13
          ports:
            - containerPort: 3000
